#  https://github.com/marketplace/actions/pr-branch-labeler
develop:
  base: ["develop/*", "develop*", "develop"]
release:
  base: ["main"]
feature:
  head: ["feature/*", "feat/*"]
fix:
  head: ["bugfix/*", "fix/*"]
hotfix:
  head: "hotfix/*"
enhancement:
  #테스트22
  head: ["enhance/*", "enhancement/*"]
