name: PR Branch Labeler

on: pull_request

permissions: write-all

jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        env:
          ACTIONS_STEP_DEBUG: true
        uses: aeong98/Pull-Request-Labeler@pre-release
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
