name: PR Branch Labeler

on: pull_request

permissions: write-all

jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        env:
          ACTIONS_STEP_DEBUG: true
#        if: github.event.action == 'opened' # Only run the action when the PR was first opened
        uses: aeong98/auto-labeler@pre-release
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
